# Generated by Django 5.1.3 on 2024-11-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='sprint_speed',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
