# Generated by Django 5.1.3 on 2024-11-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_remove_characters_spell1_remove_characters_spell2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='sprint_speed',
            field=models.IntegerField(),
        ),
    ]
