# Generated by Django 5.1.3 on 2024-11-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_characters_sprint_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells',
            name='description_image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spells',
            name='cooldown',
            field=models.ImageField(blank=True, null=True, upload_to='spells_description/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='spells',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='spells/%Y/%m/%d/'),
        ),
    ]
