# Generated by Django 5.1.3 on 2024-11-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_spells_description_image_alter_spells_cooldown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spells',
            name='cooldown',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spells',
            name='description_image',
            field=models.ImageField(blank=True, null=True, upload_to='spells_description/%Y/%m/%d/'),
        ),
    ]
