# Generated by Django 5.1.3 on 2024-11-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_alter_spells_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characters',
            options={'ordering': ['name'], 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='spells',
            options={'ordering': ['characters_id'], 'verbose_name_plural': 'Spells'},
        ),
    ]
