# Standart libraries
# Other libraries
from django.db import models
from django.shortcuts import reverse

# Project libraries


class Characters(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(
        upload_to="characters/%Y/%m/%d/", 
        default=None, blank=True, 
        null=True
        )
    story = models.TextField()
    dps = models.IntegerField()
    bullet_damage = models.DecimalField(max_digits=5, decimal_places=2)
    bullet_per_second = models.DecimalField(max_digits=5, decimal_places=2)
    ammo = models.IntegerField()
    light_melee = models.IntegerField()
    heavy_melee = models.IntegerField()
    max_health = models.IntegerField()
    health_regen = models.IntegerField()
    stamina = models.IntegerField()
    move_speed = models.DecimalField(max_digits=5, decimal_places=2)
    sprint_speed = models.IntegerField()
    bullet_resist = models.IntegerField()
    spirit_resist = models.IntegerField()
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=255)


    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name_plural = 'Characters'

    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('characters-detail', kwargs={'pk': self.pk })






# Characters.objects.bulk_create([
#     Characters(name='abrams', image='characters/2024/11/09', story="""Hard hitting, hard headed, and hard drinking; Detective Abrams has been a fixture on the New York investigating scene for years. From stolen art, to missing persons, to ritual murders; Abrams didn't just take any case that came across his desk... he solved them. But his days of following cheating spouses came to an end the day he opened his office door and found The Tome sitting on his desk.No instruction was left for him save for a brief note scrawled in onyx blood that read "Don't let them have it". Abrams hasn't figured out where the thing came from; but seeing as his home has been broken into, his office tossed on 3 different occasions, and his car firebombed he has a vested interest in figuring out what the hell is going on.""", dps=63, bullet_damage=4.68, bullet_per_second=1.67, ammo=9, light_melee=63, heavy_melee=116, max_health=570, health_regen=1, stamina=3, move_speed=6.5, bullet_resist=0, spirit_resist=0, slug='abrams', sprint_speed=0),
#     Characters(name='bebop', image='characters/2024/11/09', story="""Forged by the hands of a widowed junk yard attendant; Bebop was more than just some scrap golem laborer... he was the son she couldn't have. Together they would work in the iron yard during the day, and listen to jazz at night. But now, Bebop's creator has fallen ill and while Miss Shelly wouldn't approve of the activities that Bebop does at night to pay for her medicine, what she doesn't know can't hurt her.""", dps=66, bullet_damage=5.3, bullet_per_second=12.5, ammo=66, light_melee=63, heavy_melee=116, max_health=650, health_regen=3, stamina=3, move_speed=6.2, bullet_resist=10, spirit_resist=0, slug='bebop', sprint_speed=3),
#     Characters(name='dynamo', image='characters/2024/11/09', story="""As a Scientist, Professor Dynamo always had an inquisitive mind. So when a rift in space and time opened up in central park he was first on the scene to investigate – and while he expected such a majestic sight to be life changing, he was thinking more in a metaphorical way as opposed to having his body atomized and reduced to a tiny dying star. But while his body is gone, his spirit and lust for knowledge lives on. A tenured professor at Columbia College, Dynamo looks to learn more about his condition while maintaining his class load, after all; he has future minds to inspire""", dps=52, bullet_damage=15, bullet_per_second=4.0, ammo=18, light_melee=63, heavy_melee=116, max_health=650, health_regen=2, stamina=3, move_speed=6.5, bullet_resist=0, spirit_resist=0, slug='dynamo', sprint_speed=0),
#     Characters(name='grey talon', image='characters/2024/11/09', story="""A founding member of "The Baxter Society", Wesley Grey Talon spent close to 40 years hunting monsters that preyed on man before finally deciding to find a replacement and lay down his bow. Grey Talon’s duties had meant that he never spent much time with his wife and kid, and now that his son had started a family of his own he realized that this was his last chance to reconnect with the people he loved. Retirement suited Wesley. He made up for lost time with his wife. He doted on his grandkids. He cooked dinner for the whole family every Wednesday. He was happy. Then he got the call. The authorities claimed that it was a freak accident... that the fire consumed his son’s house before anyone got a chance to escape. But Wesley knew better. His son’s wife was Ixian... she could snuff out flame with a thought. If their bodies were found burned they had to be dead long before there was a fire. And so Grey Talon has picked up his bow once more, and when he finds who’s responsible there will be a bloody reckoning.""", dps=55, bullet_damage=27.0, bullet_per_second=2.5, ammo=17, light_melee=63, heavy_melee=116, max_health=550, health_regen=2.5, stamina=4, move_speed=6.0, bullet_resist=0, spirit_resist=0, slug='grey_talon', sprint_speed=0),
#     Characters(name='haze', image='characters/2024/11/09', story="""The Occult Security and Investigation Commission is a black box government organization that makes the CIA look transparent. It falls on the men, women, and entities of the OSIC to keep the country safe from sinister forces that are beyond the capabilities of local law enforcement. As a member of the notorious Sandman Division, Haze is routinely tasked with infiltrating the dreams of persons of interest, to assess their threat level, and if needed... to put them to sleep.""", dps=53, bullet_damage=5.6, bullet_per_second=10.0, ammo=25, light_melee=63, heavy_melee=116, max_health=500, health_regen=2, stamina=3, move_speed=8.2, bullet_resist=0, spirit_resist=0, slug='haze', sprint_speed=0),
#     Characters(name='infernus', image='characters/2024/11/09', story="""Like most teenagers; Infernus was wild, rebellious, and impetuous. Unlike most teenagers, Infernus was a creature from another planet and had a supernatural mastery over fire. Needless to say: his youth was filled with no small amount of arson, murder, and evidence disposal. But that was then. Now an adult, Infernus has mellowed out considerably. He’s happy working at a bar with good live music, and talking to interesting people. That being said when someone at the bar gets belligerent or violent, he’s not afraid to dust off the skills he once honed.""", dps=66, bullet_damage=6.6, bullet_per_second=10.0, ammo=27, light_melee=63, heavy_melee=116, max_health=600, health_regen=2, stamina=3, move_speed=6.5, bullet_resist=0, spirit_resist=0, slug='infernus', sprint_speed=0),
#     Characters(name='ivy', image='characters/2024/11/09', story="""The gargoyle didn’t know what was happening when it sprang to life... just that a big human and a small human were being hurt. And so the gargoyle leapt to action, sending the attackers fleeing in horror. The small human said thank you and asked the gargoyle’s name. The gargoyle didn’t have one. And so the small human said, "I’m going to call you Ivy." The gargoyle, being covered in ivy at the time, thought it was a bit obvious, but decided to go along with it for the small human’s sake. The humans asked if Ivy would come home with them so they could show their appreciation, and so Ivy walked with them. That night she learned much. The family were called The Arroyo's. The little one, Sophia. Mofongo is what they called a plate of deliciousness. But most importantly, she learned that the people attacking them were called "The Mendoza Syndicate", and they were hurting people…nice people like The Arroyo's. 18 years have passed since the day the Arroyo's took Ivy home... and during that she made it her mission to dismantle the Mendoza Syndicate and free Spanish Harlem from its grasp. However the thing about dedicating your life to a single pursuit for nearly 2 decades is that you don’t really know what to do once you achieve it. For the first time in her life, Ivy is prepared to venture outside of Spanish Harlem and see what the world has to offer beyond vigilante justice.""", dps=64, bullet_damage=5.0, bullet_per_second=14.3, ammo=33, light_melee=63, heavy_melee=116, max_health=550, health_regen=2, stamina=4, move_speed=7, bullet_resist=0, spirit_resist=0, slug='ivy', sprint_speed=0),
#     Characters(name='kelvin', image='characters/2024/11/09', story="""A famed adventuring scientist, Kelvin made it his life’s mission to explore and understand the unknowable. So naturally when rumors surfaced regarding an 8th astral gate hidden in the arctic, Kelvin couldn’t build an expedition team fast enough. Assembling the brightest minds of his generation, Kelvin and his team set forth with much fanfare. They never returned. A year and a half later the frozen body of Kelvin was found by a fishing trawler, his corpse clutching a rock etched with glowing runes. The crew chipped away at the ice, looking to get a closer look at the body and were shocked when Kelvin opened his eyes. They checked his vitals… there was no pulse. They sought to bandage his open wounds… there was no blood. And yet, impossibly, Kelvin was "alive". Having no memory of what happened on the expedition, Kelvin is looking for answers.""", dps=83, bullet_damage=21.0, bullet_per_second=4.0, ammo=15, light_melee=63, heavy_melee=116, max_health=600, health_regen=2, stamina=3, move_speed=6.5, bullet_resist=0, spirit_resist=10, slug='kelvin', sprint_speed=0),
#     Characters(name='lady geist', image='characters/2024/11/09', story="""Once, Lady Jeanne Geist was the toast of the town. But as time passed and her beauty faded she found herself further and further from her glory days in High Society until finally she was nothing more than a frail woman in a nursing home, telling stories of a glorious past. And that’s when Oathkeeper revealed himself. A powerful spirit from another plane, Oathkeeper offered her a path to reclaim her past glories… he could restore her youth; all she had to do was drain the essence of the living to sustain herself. Geist was torn. Obviously murder was ghoulish business, and undoubtedly Oathkeeper was not an entity that could be trusted… but still, the thought of having a second chance of reliving her youth was too good to pass up. And so she concocted a plan; after making a pact with Oathkeeper she would bind and ward him, limiting his influence and pull over her. Oathkeeper would still get fed; but on her terms, not his. However, as years have turned to decades; the strength of the Ward has weakened, and Oathkeeper hungers more than he ever has in the past...""", dps=55, bullet_damage=25.5, bullet_per_second=2.22, ammo=13, light_melee=63, heavy_melee=116, max_health=650, health_regen=1, stamina=3, move_speed=6.0, bullet_resist=0, spirit_resist=0, slug='lady_geist', sprint_speed=1.5),
#     Characters(name='lash', image='characters/2024/11/09', story="""Jacob Lash is an asshole.""", dps=61, bullet_damage=9.0, bullet_per_second=6.12, ammo=29, light_melee=63, heavy_melee=116, max_health=550, health_regen=2, stamina=3, move_speed=7.0, bullet_resist=0, spirit_resist=15, slug='lash', sprint_speed=1),
#     Characters(name='mcGinnis', image='characters/2024/11/09', story="""Maggie McGinnis always had a knack for building things. At 4 she was using Lincoln Logs to recreate architectural marvels. At 10 she built and rewired a custom light fixture for her parent's anniversary. At 15 she designed a machine that refined the souls of the dead...that last one got a little more attention than the Lincoln Logs. Now the head of Fairfax Industries Military RLORED department, McGinnis spends her time in the machine shop, not in a lab. She's not interested in theory, to her science is magic you can touch.""", dps=89, bullet_damage=7.15, bullet_per_second=12.5, ammo=66, light_melee=63, heavy_melee=116, max_health=550, health_regen=2, stamina=2, move_speed=6.5, bullet_resist=15, spirit_resist=0, slug='mcgennis', sprint_speed=0),
#     Characters(name='mirage', image='characters/2024/11/09', story="""The Djinn are one of the more curious groups of people in the modern world. Possessing great power in controlled doses, Djinn are incapable of maintaining corporeal form for longer than 48 minutes without resting within a vessel. As a result, most Djinn employ human bodyguards for transport, protection, and companionship. Mirage is one such bodyguard. Employeed by Djinn ambassador Nashala Dion, Mirage is in New York on a diplomatic mission. It's the hope of the Djinn that they can negotiate with the US government for a sale of part of Wyoming so that they can build a sovereign nation for their people.""", dps=51, bullet_damage=18.0, bullet_per_second=2.86, ammo=16, light_melee=63, heavy_melee=116, max_health=550, health_regen=2, stamina=3, move_speed=7.0, bullet_resist=0, spirit_resist=0, slug='mirage', sprint_speed=0),
#     Characters(name='mo & krill', image='characters/2024/11/09', story="""Mo and Krill are members of The Tunnel Rats, a group that help facilitate illicit trade and commerce between the boroughs thanks to a network of underground tunnels. But while most denizens the New York underworld respect the work The Rats do, every once in a while a gang tries to exploit the tunnel system for personal vendettas...that’s when Mo and Krill step in and remind the city what happens to those who disrespect their hospitality.""", dps=70, bullet_damage=11.5, bullet_per_second=6.12, ammo=29, light_melee=63, heavy_melee=116, max_health=550, health_regen=1.5, stamina=3, move_speed=7.0, bullet_resist=8, spirit_resist=0, slug='mo_and_krill', sprint_speed=0),
#     Characters(name='paradox', image='characters/2024/11/09', story="""Paradox. An artifact of time, and the name of a notorious thieves’ guild... one that prides themselves on constructing elaborate heists that target the most untouchable of individuals and institutions. What does Paradox do with the countless artifacts, state secrets, and celebrity paternity tests that they have stolen? Put it on display at pop-up museums, so that they can show the world that no one is out of Paradox’s reach. Shrouded in mystery, each member of Paradox dons a mask and takes on the organization’s name. They are everywhere. They are nowhere. And if they want something, they are inevitable.""", dps=57, bullet_damage=7.2, bullet_per_second=7.94, ammo=40, light_melee=63, heavy_melee=116, max_health=550, health_regen=2, stamina=3, move_speed=6.5, bullet_resist=0, spirit_resist=0, slug='paradox', sprint_speed=0),
#     Characters(name='pocket', image='characters/2024/11/09', story="""Arin Fairfax, the eldest heir to Fairfax Industries, has been living in hiding for the past 5 years after being shot and left for dead on their 18th birthday. Arin doesn’t know who is trying to keep them from taking control of their parent’s company... but in the avarice fueled viper’s nest that is Fairfax Industries it could be anyone. Taking on the name "Pocket", Arin desperately wants to keep their true identity a secret… not only for their own protection; but because they want to forge their own identity separate from their parents.""", dps=70, bullet_damage=5.0, bullet_per_second=2.0, ammo=11, light_melee=63, heavy_melee=116, max_health=550, health_regen=2, stamina=3, move_speed=7.0, bullet_resist=0, spirit_resist=-15, slug='pocket', sprint_speed=0),
#     Characters(name='seven', image='characters/2024/11/09', story="""When mystic energy awoke on Earth, the world changed… anything was possible. But just because anything WAS possible, didn't mean that anything SHOULD be possible. And so the government made rules. Laws. A means for US citizens to enjoy the benefits of the supernatural world in safety. But rules and laws are for lesser men. Men with limitations. Men who were not Seven. There are many rumors about what Seven did to land himself in Lost Whisper, an oubliette for the most dangerous of occultists. But there is no doubt about what happened on the night of his execution. Wards placed by the most powerful ritualists of 7 different nations... wards designed to not just prevent mystical interference with the execution, but to simultaneously obliterate Seven's soul so that it could never be contacted, resurrected, or otherwise be used by someone looking to follow in his footsteps... failed. Onlookers viewed in horror as the strongest mentalist employed by the US Army’s head popped like a grape. They screamed as Scotland Yard’s premiere occult investigator, the one who allegedly captured Seven, crumbled to ash. Seven’s body buckled and writhed against his restraints; his skin burning from eldritch electricity... and yet he would not die. He laughed. He laughed as he tore himself free from his bondage. He laughed as his captors cowered in fear. He laughed as he massacred his tormentors. He laughed as he tasted the fresh air that was denied to him for years. And he laughed when he thought about what he was going to do once he reached New York City.""", dps=70, bullet_damage=11.5, bullet_per_second=6.12, ammo=29, light_melee=63, heavy_melee=116, max_health=550, health_regen=3, stamina=3, move_speed=7.1, bullet_resist=0, spirit_resist=0, slug='seven', sprint_speed=0),
#     Characters(name='shiv', image='characters/2024/11/09', story="""A loyal member of "The Baxter Society", an international order of monster hunters, Shiv travels across North America looking to put down creatures that prey on the living. While his less polished nature and criminal past make some of the more traditional members of the Society wary, no one can deny his effectiveness.""", dps=60, bullet_damage=5.7, bullet_per_second=1.9, ammo=10, light_melee=63, heavy_melee=116, max_health=600, health_regen=2, stamina=3, move_speed=7.0, bullet_resist=0, spirit_resist=0, slug='shiv', sprint_speed=0),
#     Characters(name='vindicta', image='characters/2024/11/09', story="""A victim of John Hathorne during the Salem Witch Trials, Vindicta got a second chance of life when her spirit was brought back to the mortal plane during the first Maelstrom (the event that introduced the supernatural to the public at large). Waging a one ghost war against the "The Friends of Humanity", a neo inquisition formed by Hawthorne's descendants; Vindicta looks to keep the supernatural safe from Hathorne’s ilk, and she isn't afraid to stack as many bodies as needed to do it.""", dps=73, bullet_damage=13.0, bullet_per_second=5.26, ammo=22, light_melee=63, heavy_melee=116, max_health=550, health_regen=2, stamina=2, move_speed=9.0, bullet_resist=0, spirit_resist=0, slug='vindicta', sprint_speed=0),
#     Characters(name='viscous', image='characters/2024/11/09', story="""The Bermuda Triangle was never a myth, it was a shadowline nexus deep underneath the Atlantic Ocean. For the most part, the things that escaped this astral gate were benign (like Nessie), but now something dark and predatory hunts the seas... and its denizens are scared to death. One of those inhabitants, a psychic sea anemone, wants to do something about it. Psychically building itself an ectoplasmic goo body so it can survive on the surface, Viscous desperately is trying to summon The Patrons to keep The Deep safe from the adversary that lurks below.""", dps=70, bullet_damage=11.0, bullet_per_second=5.0, ammo=20, light_melee=63, heavy_melee=116, max_health=550, health_regen=2, stamina=3, move_speed=7.0, bullet_resist=0, spirit_resist=0, slug='viscous', sprint_speed=0),
#     Characters(name='warden', image='characters/2024/11/09', story="""Most people think the supernatural came into the world 50 years ago. They’re wrong. Its presence shaped folklore for generations... and as long as there have been people afraid of the shadows, there have been those who dedicated their lives to fighting in them. Coming from a lineage of militant alchemists, Warden’s family always trained for the day they would have to stave off a mystic apocalypse... but as time passed the importance of the lessons seemed less and less important. What once was viewed as a sincere warning slowly morphed into being perceived as amusing anecdotes told by their superstitious grandparents. When the portal opened in Central Park, Warden’s parents realized not only was everything they were told true, but they were also unprepared. Refusing to let the next generation fall asleep on the job, Warden was trained since birth to be a supernatural killing machine with one purpose: stopping the Patrons from ever entering our world.""", dps=79, bullet_damage=19.8, bullet_per_second=4.0, ammo=17, light_melee=63, heavy_melee=116, max_health=550, health_regen=2, stamina=3, move_speed=6.0, bullet_resist=0, spirit_resist=0, slug='warden', sprint_speed=0),
#     Characters(name='wraith', image='characters/2024/11/09', story="""The cornerstone of the New York gambling scene, Wraith’s organization is about as open a secret as it comes. However, thanks to a non-trivial amount of bribes, shakedowns, and blackmail, Wraith knows that she’s above the law.""", dps=61, bullet_damage=5.5, bullet_per_second=11.1, ammo=52, light_melee=63, heavy_melee=116, max_health=550, health_regen=2, stamina=3, move_speed=7.0, bullet_resist=0, spirit_resist=0, slug='wraith', sprint_speed=0),    
#     Characters(name='yamato', image='characters/2024/11/09', story="""Born into a family of crime bosses, Kaori and her brother Yamato always knew they were destined to take over control of the Seventh Moon after their father's death. Together they ran the organization for years, bringing it profit and success, and even planning an expansion into America. The plan was simple: Kaori would remain in Japan to control the country, while Yamato would travel to America to establish an international base. Unfortunately for the siblings, some of their subordinates were not happy about Kaori's plan to take command in Japan. The rebellion was swift and violent. Yamato sacrificed his life to protect Kaori, and Kaori was saved by a handful of loyal members. Together with her subordinates, she managed to escape from Japan to the United States. When Kaori and her group arrived in the United States, they were greeted by a man who was supposed to greet Yamato. He was not familiar with Japanese names and did not know Kaori. "Yamato." Kaori thought about correcting his mistake, but... She decided that the best way to remember her brother was to take on the Yamato name and make his dream come true.""", dps=70, bullet_damage=5.65, bullet_per_second=2.5, ammo=12, light_melee=69, heavy_melee=128, max_health=500, health_regen=2, stamina=3, move_speed=8.0, bullet_resist=0, spirit_resist=0, slug='yamato', sprint_speed=0)    
# ])