# Generated by Django 5.1.3 on 2024-11-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_map_icons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='images_city',
        ),
    ]
