# Generated by Django 5.1.3 on 2024-11-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'City'},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name_plural': 'Map'},
        ),
    ]
