# Generated by Django 5.1.3 on 2024-11-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='images_city',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='map/%Y/%m/%d/'),
        ),
    ]
