# Generated by Django 5.1.3 on 2024-11-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_map_images_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='icons',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='map/%Y/%m/%d/'),
        ),
    ]
