# Generated by Django 5.1.3 on 2024-11-09 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='characters/%Y/%m/%d/')),
                ('story', models.TextField()),
                ('spell1', models.CharField(max_length=255)),
                ('spell2', models.CharField(max_length=255)),
                ('spell3', models.CharField(max_length=255)),
                ('spellultimate', models.CharField(max_length=255)),
                ('dps', models.IntegerField()),
                ('bullet_damage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bullet_per_second', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ammo', models.IntegerField()),
                ('light_melee', models.IntegerField()),
                ('heavy_melee', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('health_regen', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('move_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bullet_resist', models.IntegerField()),
                ('spirit_resist', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='characters__name_a10eee_idx')],
            },
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cooldown', models.IntegerField()),
                ('activity', models.BooleanField(blank=True, default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='characters/%Y/%m/%d/')),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.characters')),
            ],
        ),
    ]
