# Generated by Django 5.1.3 on 2024-11-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_alter_spells_cooldown_alter_spells_description_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells',
            name='slug',
            field=models.SlugField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
