# Generated by Django 5.1.3 on 2024-11-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_spells_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells',
            name='spell_number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
