# Generated by Django 5.1.3 on 2024-11-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_spells_spell_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spells',
            name='activity',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='spells',
            name='cooldown',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
