# Generated by Django 5.1.3 on 2024-11-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_alter_spells_activity_alter_spells_cooldown'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spells',
            options={'ordering': ['characters_id']},
        ),
    ]
