# Generated by Django 5.1.3 on 2024-11-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='shop/%Y/%m/%d/')),
                ('category', models.CharField(max_length=255)),
                ('activity', models.BooleanField(blank=True, default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['price'],
                'indexes': [models.Index(fields=['price'], name='shop_shop_price_5ac662_idx')],
            },
        ),
    ]
