# Generated by Django 5.1.3 on 2024-11-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['price'], 'verbose_name_plural': 'Shop'},
        ),
    ]
